-- =============================================================================
-- Competitive Intelligence System — PostgreSQL Schema
-- Drop and recreate all tables (idempotent migration)
-- =============================================================================

-- Enable UUID generation
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- -----------------------------------------------------------------------------
-- 1. target_cache — caches scraped data for target sites
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS target_cache CASCADE;

CREATE TABLE target_cache (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    url         TEXT NOT NULL,
    domain      TEXT,
    scraped_data JSONB,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at  TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '24 hours')
);

CREATE INDEX idx_target_cache_domain_expires
    ON target_cache (domain, expires_at);

COMMENT ON TABLE target_cache IS 'Caches scraped product catalog and metadata for target ecommerce sites. TTL = 24 hours.';

-- -----------------------------------------------------------------------------
-- 2. competitor_cache — caches scraped data for discovered competitor sites
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS competitor_cache CASCADE;

CREATE TABLE competitor_cache (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    domain       TEXT NOT NULL,
    url          TEXT,
    scraped_data JSONB,
    api_data     JSONB,   -- PageSpeed, BuiltWith, DataForSEO backlinks, Clearbit, etc.
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at   TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '24 hours')
);

CREATE INDEX idx_competitor_cache_domain_expires
    ON competitor_cache (domain, expires_at);

COMMENT ON TABLE competitor_cache IS 'Caches scraped and API-enriched data for competitor sites. TTL = 24 hours.';

-- -----------------------------------------------------------------------------
-- 3. reports — stores generated competitive intelligence reports
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS reports CASCADE;

CREATE TABLE reports (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    target_url       TEXT NOT NULL,
    target_domain    TEXT,
    report_data      JSONB,   -- full report JSON from n8n AI Intelligence Suite
    pdf_url          TEXT,    -- link to generated PDF (PDFShift)
    competitor_count INT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_reports_target_domain_created
    ON reports (target_domain, created_at DESC);

COMMENT ON TABLE reports IS 'Stores full competitive intelligence reports generated by the n8n workflow.';

-- -----------------------------------------------------------------------------
-- 4. run_log — tracks every workflow execution
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS run_log CASCADE;

CREATE TABLE run_log (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    target_url     TEXT,
    status         TEXT NOT NULL DEFAULT 'running'
                       CHECK (status IN ('running', 'completed', 'failed')),
    triggered_by   TEXT CHECK (triggered_by IN ('webhook', 'schedule', 'dashboard')),
    started_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at   TIMESTAMPTZ,
    error_message  TEXT,
    report_id      UUID REFERENCES reports(id) ON DELETE SET NULL
);

CREATE INDEX idx_run_log_status ON run_log (status);
CREATE INDEX idx_run_log_started_at ON run_log (started_at DESC);

COMMENT ON TABLE run_log IS 'Tracks every n8n workflow execution: status, timing, errors, and linked report.';

-- -----------------------------------------------------------------------------
-- Helper view: active (non-expired) caches
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW active_target_cache AS
    SELECT * FROM target_cache WHERE expires_at > NOW();

CREATE OR REPLACE VIEW active_competitor_cache AS
    SELECT * FROM competitor_cache WHERE expires_at > NOW();

-- =============================================================================
-- Done
-- =============================================================================
